artem_blog_post:
    resource: "@artemBlogBundle/Resources/config/routing/post.yml"
    prefix:   /post

artem_blog_homepage:
    path:     /
    defaults: { _controller: artemBlogBundle:Default:index }
